export const mockFilmsResponse = {
  data: {
    count: 6,
    pages: 1,
    next: null,
    previous: null,
    results: [
      {
        fields: {
          starships: [
            "/api/starships/2",
            "/api/starships/3",
            "/api/starships/5",
            "/api/starships/9",
            "/api/starships/10",
            "/api/starships/11",
            "/api/starships/12",
            "/api/starships/13",
          ],
          edited: "2014-12-20T19:49:45.256Z",
          vehicles: [
            "/api/vehicles/4",
            "/api/vehicles/6",
            "/api/vehicles/7",
            "/api/vehicles/8",
          ],
          planets: ["/api/planets/1", "/api/planets/2", "/api/planets/3"],
          producer: "Gary Kurtz, Rick McCallum",
          title: "A New Hope",
          created: "2014-12-10T14:23:31.880Z",
          episode_id: 4,
          director: "George Lucas",
          release_date: "1977-05-25",
          opening_crawl:
            "It is a period of civil war.\r\nRebel spaceships, striking\r\nfrom a hidden base, have won\r\ntheir first victory against\r\nthe evil Galactic Empire.\r\n\r\nDuring the battle, Rebel\r\nspies managed to steal secret\r\nplans to the Empire's\r\nultimate weapon, the DEATH\r\nSTAR, an armored space\r\nstation with enough power\r\nto destroy an entire planet.\r\n\r\nPursued by the Empire's\r\nsinister agents, Princess\r\nLeia races home aboard her\r\nstarship, custodian of the\r\nstolen plans that can save her\r\npeople and restore\r\nfreedom to the galaxy....",
          characters: [
            "/api/people/1",
            "/api/people/2",
            "/api/people/3",
            "/api/people/4",
            "/api/people/5",
            "/api/people/6",
            "/api/people/7",
            "/api/people/8",
            "/api/people/9",
            "/api/people/10",
            "/api/people/12",
            "/api/people/13",
            "/api/people/14",
            "/api/people/15",
            "/api/people/16",
            "/api/people/18",
            "/api/people/19",
            "/api/people/81",
          ],
          species: [
            "/api/species/1",
            "/api/species/2",
            "/api/species/3",
            "/api/species/4",
            "/api/species/5",
          ],
          url: "/api/films/1",
        },
      },
      {
        fields: {
          starships: [
            "/api/starships/3",
            "/api/starships/10",
            "/api/starships/11",
            "/api/starships/12",
            "/api/starships/15",
            "/api/starships/17",
            "/api/starships/21",
            "/api/starships/22",
            "/api/starships/23",
          ],
          edited: "2014-12-15T13:07:53.386Z",
          vehicles: [
            "/api/vehicles/8",
            "/api/vehicles/14",
            "/api/vehicles/16",
            "/api/vehicles/18",
            "/api/vehicles/19",
            "/api/vehicles/20",
          ],
          planets: [
            "/api/planets/4",
            "/api/planets/5",
            "/api/planets/6",
            "/api/planets/27",
          ],
          producer: "Gary Kurtz, Rick McCallum",
          title: "The Empire Strikes Back",
          created: "2014-12-12T11:26:24.656Z",
          episode_id: 5,
          director: "Irvin Kershner",
          release_date: "1980-05-17",
          opening_crawl:
            "It is a dark time for the\r\nRebellion. Although the Death\r\nStar has been destroyed,\r\nImperial troops have driven the\r\nRebel forces from their hidden\r\nbase and pursued them across\r\nthe galaxy.\r\n\r\nEvading the dreaded Imperial\r\nStarfleet, a group of freedom\r\nfighters led by Luke Skywalker\r\nhas established a new secret\r\nbase on the remote ice world\r\nof Hoth.\r\n\r\nThe evil lord Darth Vader,\r\nobsessed with finding young\r\nSkywalker, has dispatched\r\nthousands of remote probes into\r\nthe far reaches of space....",
          characters: [
            "/api/people/1",
            "/api/people/2",
            "/api/people/3",
            "/api/people/4",
            "/api/people/5",
            "/api/people/10",
            "/api/people/13",
            "/api/people/14",
            "/api/people/18",
            "/api/people/20",
            "/api/people/21",
            "/api/people/22",
            "/api/people/23",
            "/api/people/24",
            "/api/people/25",
            "/api/people/26",
          ],
          species: [
            "/api/species/1",
            "/api/species/2",
            "/api/species/3",
            "/api/species/6",
            "/api/species/7",
          ],
          url: "/api/films/2",
        },
      },
    ],
  },
};

export const mockFilmResponse = {
  data: {
    starships: [
      "/api/starships/2",
      "/api/starships/3",
      "/api/starships/10",
      "/api/starships/11",
      "/api/starships/12",
      "/api/starships/15",
      "/api/starships/17",
      "/api/starships/22",
      "/api/starships/23",
      "/api/starships/27",
      "/api/starships/28",
      "/api/starships/29",
    ],
    edited: "2014-12-20T09:48:37.462Z",
    vehicles: [
      "/api/vehicles/8",
      "/api/vehicles/16",
      "/api/vehicles/18",
      "/api/vehicles/19",
      "/api/vehicles/24",
      "/api/vehicles/25",
      "/api/vehicles/26",
      "/api/vehicles/30",
    ],
    planets: [
      "/api/planets/1",
      "/api/planets/5",
      "/api/planets/7",
      "/api/planets/8",
      "/api/planets/9",
    ],
    producer: "Howard G. Kazanjian, George Lucas, Rick McCallum",
    title: "Return of the Jedi",
    created: "2014-12-18T10:39:33.255Z",
    episode_id: 6,
    director: "Richard Marquand",
    release_date: "1983-05-25",
    opening_crawl:
      "Luke Skywalker has returned to\r\nhis home planet of Tatooine in\r\nan attempt to rescue his\r\nfriend Han Solo from the\r\nclutches of the vile gangster\r\nJabba the Hutt.\r\n\r\nLittle does Luke know that the\r\nGALACTIC EMPIRE has secretly\r\nbegun construction on a new\r\narmored space station even\r\nmore powerful than the first\r\ndreaded Death Star.\r\n\r\nWhen completed, this ultimate\r\nweapon will spell certain doom\r\nfor the small band of rebels\r\nstruggling to restore freedom\r\nto the galaxy...",
    characters: [
      "/api/people/1",
      "/api/people/2",
      "/api/people/3",
      "/api/people/4",
      "/api/people/5",
      "/api/people/10",
      "/api/people/13",
      "/api/people/14",
      "/api/people/16",
      "/api/people/18",
      "/api/people/20",
      "/api/people/21",
      "/api/people/22",
      "/api/people/25",
      "/api/people/27",
      "/api/people/28",
      "/api/people/29",
      "/api/people/30",
      "/api/people/31",
      "/api/people/45",
    ],
    species: [
      "/api/species/1",
      "/api/species/2",
      "/api/species/3",
      "/api/species/5",
      "/api/species/6",
      "/api/species/8",
      "/api/species/9",
      "/api/species/10",
      "/api/species/15",
    ],
    url: "/api/films/3",
  },
};
